### PR TITLE
Remove references to non-existent font "OpenSans-Extra.ttf"

### PR DESCRIPTION
**Pull request by owenjonesuob**
The stylesheets for both the 4x3 and 16x10 screen ratio styles make references to a number of fonts. One of these, "OpenSans-Extra", [doesn't actually exist](https://fonts.google.com/specimen/Open+Sans).

This caused attempts to knit a shower presentation from a Rmarkdown document while using `theme: mango` to fail thusly:

```
pandoc.exe: Could not fetch h2o_pres_files/rmdshower.mango/package/styles\../fonts/Open_Sans/OpenSans-Extra.ttf
h2o_pres_files/rmdshower.mango/package/styles\../fonts/Open_Sans/OpenSans-Extra.ttf: openBinaryFile: does not exist (No such file or directory)
Error: pandoc document conversion failed with error 67
In addition: Warning messages:
[... etc.]
```

No more shall we be terrorised by intimidating error messages. I have removed the offending references from the CSS and SCSS files, thereby facilitating Consistent Avoidance of Knit Errors™.

_(Since this font never existed in the first place, removing references to it shouldn't have any adverse effects.)_

### CODE REVIEW

**Comment by dougmet** [comment]
Will review when I get back to a desk. Looks good though. I can't remember where OpenSans extra comes in.

**Comment by dougmet** [comment]
Smashing, can you bump the version to `2.0.1`? Then I'll merge.

**Review by dougmet — CHANGES_REQUESTED** [review]
Version bump and it can go

**Comment by owenjonesuob** [comment]
Version number updated in DESCRIPTION file - I think that's the only place it appears but let me know if I've missed something!

**Review by dougmet — APPROVED** [review]

**Pull request merged**
